HTTP/1.1 200 OK
Date: Sun, 09 Jun 2024 10:45:53 GMT
Content-Type: application/json
Transfer-Encoding: chunked
Connection: close
Vary: Accept-Encoding
Server: BunnyCDN-SG1-944
CDN-PullZone: 93447
CDN-Uid: 8fa3a04a-75d9-4707-8056-b7b33c8ac7fe
CDN-RequestCountryCode: PH
Age: 0
Cache-Control: public, max-age=180
Via: 1.1 varnish (Varnish/6.0)
x-weatherapi-qpm-left: 999991
X-Varnish: 75943713
CDN-ProxyVer: 1.04
CDN-RequestPullSuccess: True
CDN-RequestPullCode: 200
CDN-CachedAt: 06/09/2024 10:45:53
CDN-EdgeStorageId: 980
CDN-Status: 200
CDN-RequestId: 75e3c2e9a74d15b6d281469c2f64f85b
CDN-Cache: MISS
Content-Encoding: gzip

{"location":{"name":"Caloocan","region":"Caloocan","country":"Philippines","lat":14.65,"lon":120.98,"tz_id":"Asia/Manila","localtime_epoch":1717929912,"localtime":"2024-06-09 18:45"},"current":{"last_updated_epoch":1717929900,"last_updated":"2024-06-09 18:45","temp_c":29.1,"temp_f":84.4,"is_day":0,"condition":{"text":"Partly cloudy","icon":"//cdn.weatherapi.com/weather/64x64/night/116.png","code":1003},"wind_mph":2.2,"wind_kph":3.6,"wind_degree":201,"wind_dir":"SSW","pressure_mb":1010.0,"pressure_in":29.83,"precip_mm":0.73,"precip_in":0.03,"humidity":75,"cloud":75,"feelslike_c":33.9,"feelslike_f":93.0,"vis_km":10.0,"vis_miles":6.0,"uv":6.0,"gust_mph":9.4,"gust_kph":15.2}}
